from enum import Enum


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    VALIDATING = "VALIDATING"
    DOWNLOADING = "DOWNLOADING"
    EXTRACTING_AUDIO = "EXTRACTING_AUDIO"
    TRANSCRIBING = "TRANSCRIBING"
    ANALYZING = "ANALYZING"
    DETECTING_VIBES = "DETECTING_VIBES"
    GENERATING_VIBES = "GENERATING_VIBES"
    FINALIZING = "FINALIZING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


ACTIVE_JOB_STATUSES = {
    JobStatus.QUEUED,
    JobStatus.VALIDATING,
    JobStatus.DOWNLOADING,
    JobStatus.EXTRACTING_AUDIO,
    JobStatus.TRANSCRIBING,
    JobStatus.ANALYZING,
    JobStatus.DETECTING_VIBES,
    JobStatus.GENERATING_VIBES,
    JobStatus.FINALIZING,
}
